### ISSUE TITLE
Probleme CDR retour.

### ISSUE THREAD

**Issue by xorgxx** [rollincode/RCPaiementCMCICBundle#7]
Bonjour, en test tout fonction bien. je veux passer en mode prod la le CM ne dit que les codes de retour sont faux !??? (ver = 2; cdr = 015)

Merci d'une aide.

**Comment by nicovak** [comment]
As-tu vérifié l'url de prod ? Et la version ? `SERVEUR_PREPROD` et `VERSION`
Dans `app/config/services.yml`

````
serveur:
    # URL pour la prod ex: "https://ssl.paiement.cic-banques.fr/"
    SERVEUR_PROD: "MON_URL"
    # URL pour la préprod ex: "https://ssl.paiement.cic-banques.fr/test/"
    SERVEUR_PREPROD: "MON_URL"
    VERSION: "3.0"
````
